[book]
language = "uk"
multilingual = false
src = "docs"

# Замініть авторство проєкта на своє
authors = ["Sofia Kulichenko", "Yevheniy Onischenko", "Ivan Braslavets", "Nazar Komaretskyi", "Vadim Malish", "Mykyta Panov", "Pavlo Rogatkin"]

# Змініть назву проєкта на свою
title = "OmezhkaControl"

[preprocessor.plantuml]
plantuml-cmd = "http://www.plantuml.com/plantuml"
use-data-uris = true
